### ISSUE TITLE
Prefixer throws warnings on unsupported CSS properties

### ISSUE THREAD

**Issue by xml** [mvila/radium-normalize#1]
Hi! Thanks for radium-normalize!

It's working great for me. I'm just wondering if there's a way to suppress/avoid some warnings it's throwing in the console in my react/redux/webpack/radium project:

```
Unsupported CSS property "msTextSizeAdjust$" in component "Style"
Unsupported CSS property "WebkitTextSizeAdjust$" in component "Style"
```

Both are sourced from `prefixer.js:394`

I think all of that processing is happening in dependencies that are local to radium-normalize, but let me know if you need my package.json or webpack.config.

**Comment by mvila** [comment]
When do you see these warnings? At build time or in the browser?

What version of React/Radium do you use? I just tested with the last versions (React 0.14.7/Radium 0.17.0) and I cannot see any warning.
