### ISSUE TITLE
Module parse failed (webpack)

### ISSUE THREAD

**Issue by paragonbliss** [mvila/radium-normalize#2]
I don't know if this is the appropriate place to ask about this issue, but i tried using your library with webpack, and i am getting this error

```
ERROR in ./~/radium-normalize/normalize.json
Module parse failed: /Users/michael/movir/node_modules/radium-normalize/normalize.json Unexpected token (2:8)
```

I tried putting a json-loader in my webpack config but that did not help the issue, i am not sure what is going on here.

**Comment by mvila** [comment]
Thanks @paragonbliss for your feedback. I don't know if Webpack can handle .json files correctly, I have no problem with Browserify. If you have time to investigate more, please let me know what you find.

**Comment by RobertBolender** [comment]
I received the same error from radium-normalize when I first tried to use webpack with radium-starter.

All that I had to do was run `npm install --save json-loader` and then add this line to my webpack.config.js:

``` js
{ test: /\.json$/, loader: "json-loader" }
```

**Comment by mvila** [comment]
Thanks @awesomebob!

**Comment by mvila** [comment]
Finally, I gave up the idea of using a `.json` file. Should be fine now using Webpack without `json-loader`.
